version: '3.1'

services:
  app_transaction:
    container_name: app_transaction
    mem_limit: 512m
    image: pee-app_transaction:0.0.1
    build: .
    ports:
      - 8083:8083
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: fraud
    volumes:
      - ./data:/data/db/
      - ./data/log:/var/log/mongodb/
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: sa
      ME_CONFIG_BASICAUTH_PASSWORD: sa
    links:
      - mongo
    ports:
      - 8081:8081